modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="thecroodaceousera" #mandatory
version="${file.jarVersion}" #mandatory
displayName="The Croodaceous Era" #mandatory
credits="Coda, VakyPanda, SimplePotato, Dia Monde, Ash" #optional
description='''
This mod brings content from The Croods movie into Minecraft!'''