modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="croodaceouscraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Croodaceous Craft" #mandatory
credits="Coda, SimplePotato, Dia Monde, Ash" #optional
description='''
This mod aims to bring content from The Croods movie into Minecraft!'''